import * as dotenv from 'dotenv';
dotenv.config(); // Load .env file

const CONSTANTS = {
  APPLICATION: {
    STATUS: {
      QUALIFYING_TEST_PASSED: 'qualifyingTestPassed',
      QUALIFYING_TEST_FAILED: 'qualifyingTestFailed',
      SCENARIO_TEST_PASSED: 'scenarioTestPassed',
      SCENARIO_TEST_FAILED: 'scenarioTestFailed',
      SIFT_PASSED: 'siftPassed',
      SIFT_FAILED: 'siftFailed',
      SELECTION_INVITED: 'selectionInvited',
      REJECTED_INELIGIBLE_STATUTORY: 'rejectedIneligibleStatutory',
      REJECTED_INELIGIBLE_ADDITIONAL: 'rejectedIneligibleAdditional',
      REJECTED_CHARACTER: 'rejectedCharacter',
      WITHDRAWN: 'withdrawn',
      SELECTION_PASSED: 'selectionPassed',
      SELECTION_FAILED: 'selectionFailed',
      PASSED_RECOMMENDED: 'passedRecommended',
      PASSED_NOT_RECOMMENDED: 'passedNotRecommended',
      RECOMMENDED_IMMEDIATE: 'recommendedImmediate',
      RECOMMENDED_FUTURE: 'recommendedFuture',
      RECONSIDER: 'reconsider',
      SECOND_STAGE_INVITED: 'secondStageInvited',
      SCC_TO_RECONSIDER: 'sccToReconsider',
    },
    CHARACTER_ISSUES: { // this gives a map from issue to corresponding details field TODO improve naming or where we store this
      drivingDisqualificationDrinkDrugs: {
        group: 'Motoring Offences',
        title: 'Driving Disqualification Drink Drugs',
        details: 'drivingDisqualificationDrinkDrugsDetails',
        summary: 'Candidate has been disqualified from driving, or convicted for driving under the influence of drink or drugs',
      },
      endorsementsOrMotoringFixedPenalties: {
        group: 'Motoring Offences',
        title: 'Endorsements Or Motoring Fixed Penalties',
        details: 'endorsementsOrMotoringFixedPenaltiesDetails',
        summary: 'Candidate has endorsements on their licence, or received any motoring fixed-penalty notices in the last 4 years',
      },
      nonMotoringFixedPenaltyNotices: {
        group: 'Motoring Offences',
        title: 'Non Motoring Fixed Penalty Notices',
        details: 'nonMotoringFixedPenaltyNoticesDetails',
        summary: 'Candidate has received a non-motoring penalty notice in the last 4 years',
      },
      criminalOffences: {
        group: 'Criminal Offences',
        title: 'Criminal Offences',
        details: 'criminalOffenceDetails',
        summary: 'Candidate has been cautioned or convicted of a criminal offence',
      },
      declaredBankruptOrIVA: {
        group: 'Financial Matters',
        title: 'Declared Bankrupt Or IVA',
        details: 'declaredBankruptOrIVADetails',
        summary: 'Candidate has been declared bankrupt or entered into an Individual Voluntary Agreement (IVA)',
      },
      lateTaxReturnOrFined: {
        group: 'Financial Matters',
        title: 'Late Tax Return Or Fined',
        details: 'lateTaxReturnOrFinedDetails',
        summary: 'Candidate has filed late tax returns or been fined by HMRC',
      },
      diciplinaryActionOrAskedToResign: {
        group: 'Professional Conduct',
        title: 'Disciplinary Action Or Asked To Resign',
        details: 'diciplinaryActionOrAskedToResignDetails',
        summary: 'Candidate has been subject to complaints or disciplinary action, or been asked to resign from a position',
      },
      involvedInProfessionalMisconduct: {
        group: 'Professional Conduct',
        title: 'Involved In Professional Misconduct',
        details: 'involvedInProfessionalMisconductDetails',
        summary: 'Candidate has been, or is currently, subject to professional misconduct, negligence, wrongful dismissal, discrimination or harassment proceedings',
      },
      otherCharacterIssues: {
        group: 'Further Information to be disclosed',
        title: 'Other Character Issues',
        details: 'otherCharacterIssuesDetails',
        summary: 'Candidate has declared other issues we should know about',
      },
    },
    CHARACTER_ISSUES_V2: { // this gives a map from issue to corresponding details field TODO improve naming or where we store this
      drivingDisqualifications: {
        group: 'Motoring Offences',
        title: 'Driving Disqualifications',
        details: 'drivingDisqualificationDetails',
        summary: 'Candidate has been disqualified from driving',
        category: 'Driving Disqualifications',
      },
      recentDrivingConvictions: {
        group: 'Motoring Offences',
        title: 'Recent Driving Convictions',
        details: 'recentDrivingConvictionDetails',
        summary: 'Candidate has recent driving convictions',
        category: 'Recent Driving Convictions',
      },
      fixedPenalties: {
        group: 'Fixed Penalty Notices',
        title: 'Fixed Penalties',
        details: 'fixedPenaltyDetails',
        summary: 'Candidate has received a fixed-penalty',
        category: 'Fixed Penalties',
      },
      criminalConvictions: {
        group: 'Criminal Offences',
        title: 'Criminal Convictions',
        details: 'criminalConvictionDetails',
        summary: 'Candidate has been convicted of a criminal offence',
        category: 'Criminal Convictions',
      },
      criminalCautions: {
        group: 'Criminal Offences',
        title: 'Criminal Cautions',
        details: 'criminalCautionDetails',
        summary: 'Candidate has been cautioned for a criminal offence',
        category: 'Criminal Cautions',
      },
      bankruptcies: {
        group: 'Financial Matters',
        title: 'Bankruptcies',
        details: 'bankruptcyDetails',
        summary: 'Candidate has filed for bankruptcy',
        category: 'Bankruptcies',
      },
      ivas: {
        group: 'Financial Matters',
        title: 'IVAs',
        details: 'ivaDetails',
        summary: 'Candidate has been entered into an Individual Voluntary Agreement (IVA)',
        category: 'IVAs',
      },
      lateTaxReturns: {
        group: 'Financial Matters',
        title: 'Late Tax Returns',
        details: 'lateTaxReturnDetails',
        summary: 'Candidate has filed late tax returns',
        category: 'Late Tax Returns',
      },
      lateVatReturns: {
        group: 'Financial Matters',
        title: 'Late VAT Returns',
        details: 'lateVatReturnDetails',
        summary: 'Candidate has filed late VAT returns',
        category: 'Late VAT Returns',
      },
      hmrcFines: {
        group: 'Financial Matters',
        title: 'HMRC Fines',
        details: 'hmrcFineDetails',
        summary: 'Candidate has received a fine from HMRC',
        category: 'HMRC Fines',
      },
      subjectOfAllegationOrClaimOfProfessionalMisconduct: {
        group: 'Professional Conduct',
        title: 'Subject Of Allegation Or Claim Of Professional Misconduct',
        details: 'subjectOfAllegationOrClaimOfProfessionalMisconductDetails',
        summary: 'Candidate has been the subject of allegation or claim of misconduct',
        category: 'Professional Misconduct',
      },
      subjectOfAllegationOrClaimOfNegligence: {
        group: 'Professional Conduct',
        title: 'Subject Of Allegation Or Claim Of Negligence',
        details: 'subjectOfAllegationOrClaimOfNegligenceDetails',
        summary: 'Candidate has been the subject of allegation or claim of negligence',
        category: 'Professional Negligence',
      },
      subjectOfAllegationOrClaimOfWrongfulDismissal: {
        group: 'Professional Conduct',
        title: 'Subject Of Allegation Or Claim Of Wrongful Dismissal',
        details: 'subjectOfAllegationOrClaimOfWrongfulDismissalDetails',
        summary: 'Candidate has been the subject of allegation or claim wrongful dismissal',
        category: 'Wrongful Dismissal',
      },
      subjectOfAllegationOrClaimOfDiscriminationProceeding: {
        group: 'Professional Conduct',
        title: 'Subject Of Allegation Or Claim Of Discrimination Proceeding',
        details: 'subjectOfAllegationOrClaimOfDiscriminationProceedingDetails',
        summary: 'Candidate subject of allegation or claim of discrimination proceeding',
        category: 'Discrimination Proceedings',
      },
      subjectOfAllegationOrClaimOfHarassmentProceeding: {
        group: 'Professional Conduct',
        title: 'Subject Of Allegation Or Claim Of Harassment Proceeding',
        details: 'subjectOfAllegationOrClaimOfHarassmentProceedingDetails',
        summary: 'Candidate is subject of allegation or claim of harassment proceeding',
        category: 'Harassment Proceedings',
      },
      complaintOrDisciplinaryAction: {
        group: 'Professional Conduct',
        title: 'Complaint Or Disciplinary Action',
        details: 'complaintOrDisciplinaryActionDetails',
        summary: 'Candidate has received a complaint or disciplinary action',
        category: 'Complaints/Disciplinary',
      },
      requestedToResign: {
        group: 'Professional Conduct',
        title: 'Requested To Resign',
        details: 'requestedToResignDetails',
        summary: 'Candidate has been requested to resign',
        category: 'Asked to Resign',
      },
      furtherInformation: {
        group: 'Further Information to be disclosed',
        title: 'Further Information',
        details: 'furtherInformationDetails',
        summary: 'Candidate has declared further information',
      },
    },
    CHARACTER_ISSUE_STATUS: {
      PROCEED: 'proceed',
      REJECT: 'reject',
      REJECT_NON_DECLARATION: 'reject-non-declaration',
      DISCUSS: 'discuss',
    },
    CHARACTER_ISSUE_OFFENCE_CATEGORY: {
      SINGLE_MOTORING_OFFENCE: 'singleMotoringOffence',
      MULTIPLE_MOTORING_OFFENCES: 'multipleMotoringOffences',
      SINGLE_PENALTY_NOTICE: 'singlePenaltyNotice',
      MULTIPLE_PENALTY_NOTICES: 'multiplePenaltyNotices',
      SINGLE_CRIMINAL_OFFENCE: 'singleCriminalOffence',
      MULTIPLE_CRIMINAL_OFFENCES: 'multipleCriminalOffences',
      SINGLE_FINANCIAL_OFFENCE: 'singleFinancialOffence',
      MULTIPLE_FINANCIAL_OFFENCES: 'multipleFinancialOffences',
      SINGLE_PROFESSIONAL_CONDUCT: 'singleProfessionalConduct',
      MULTIPLE_PROFESSIONAL_CONDUCTS: 'multipleProfessionalConducts',
      SINGLE_OTHER_MATTER: 'singleOtherMatter',
      MULTIPLE_OTHER_MATTERS: 'multipleOtherMatters',
      MIXED: 'mixed',
    },
    GUIDANCE_REFERENCE: {
      CRIMINAL_OFFENCES: 'criminalOffences',
      MOTERING_OFFENCES: 'moteringOffences',
      FIXED_PENALTY_NOTICES: 'fixedPenaltyNotices',
      FINANCIAL_INSOLVENCY_DEBT: 'financialInsolvencyDebt',
      FINANCIAL_VAT_TAX: 'financialVatTax',
      PROFESSIONAL_CONDUCT: 'professionalConduct',
      FURTHER_DISCLOSURES: 'furtherDisclosures',
    },
    GUIDANCE_REFERENCE_V2: {
      CRIMINAL_OFFENCES: 'criminalOffencesV2',
      MOTERING_OFFENCES: 'moteringOffencesV2',
      FIXED_PENALTY_NOTICES: 'fixedPenaltyNoticesV2',
      FINANCIAL_INSOLVENCY_DEBT: 'financialInsolvencyDebtV2',
      FINANCIAL_VAT_TAX: 'financialVatTaxV2',
      PROFESSIONAL_CONDUCT: 'professionalConductV2',
      CIVIL_PROCEEDINGS: 'civilProceedingsV2',
      FURTHER_DISCLOSURES: 'furtherDisclosuresV2',
    },
    ELIGIBILITY_ISSUE_STATUS: {
      PROCEED: 'proceed',
      REJECT: 'reject',
      REJECT_NON_DECLARATION: 'reject-non-declaration',
      DISCUSS: 'discuss',
    },
  },
  ASSESSMENT_METHOD: {
    SELF_ASSESSMENT_WITH_COMPETENCIES: 'selfAssessmentWithCompetencies',
    COVERING_LETTER: 'coveringLetter',
    CV: 'cv',
    STATEMENT_OF_SUITABILITY_WITH_COMPETENCIES: 'statementOfSuitabilityWithCompetencies',
    STATEMENT_OF_SUITABILITY_WITH_SKILLS_AND_ABILITIES: 'statementOfSuitabilityWithSkillsAndAbilities',
    STATEMENT_OF_ELIGIBILITY: 'statementOfEligibility',
    INDEPENDENT_ASSESSMENTS: 'independentAssessments',
    LEADERSHIP_JUDGE_ASSESSMENT: 'leadershipJudgeAssessment',
  },
  ASSESSMENT_TYPE: {
    COMPETENCY: 'competency',
    SKILLS: 'skills',
    GENERAL: 'general',
  },
  SHORTLISTING: {
    TELEPHONE_ASSESSMENT: 'telephone-assessment',
    SITUATIONAL_JUDGEMENT_QUALIFYING_TEST: 'situational-judgement-qualifying-test',
    CRITICAL_ANALYSIS_QUALIFYING_TEST: 'critical-analysis-qualifying-test',
    SCENARIO_TEST_QUALIFYING_TEST: 'scenario-test-qualifying-test',
    NAME_BLIND_PAPER_SIFT: 'name-blind-paper-sift',
    PAPER_SIFT: 'paper-sift',
    OTHER: 'other',
  },
  QUALIFYING_TEST: {
    TYPE: {
      SCENARIO: 'scenario',
      CRITICAL_ANALYSIS: 'critical-analysis',
      SITUATIONAL_JUDGEMENT: 'situational-judgement',
    },
    MODE: {
      DRY_RUN: 'dry-run',
      MOP_UP: 'mop-up',
    },
    STATUS: {
      CREATED: 'created',
      SUBMITTED: 'submitted-for-approval',
      APPROVED: 'approved',
      INITIALISED: 'initialised',
      ACTIVATED: 'activated',
      PAUSED: 'paused',
      COMPLETED: 'completed',
    },
  },
  QUALIFYING_TEST_RESPONSES: {
    STATUS: {
      CREATED: 'created',
      ACTIVATED: 'activated',
      STARTED: 'started',
      COMPLETED: 'completed',
      CANCELLED: 'cancelled',
    },
  },
  PANEL_STATUS: {
    // TODO include all statuses
    DRAFT: 'draft',
    APPROVED: 'approved',
    PROCESSING: 'processing',
    CREATED: 'created',
    SUBMITTED: 'submitted',
  },
  CAPABILITIES: ['L', 'EJ', 'L&J', 'PQ', 'PBK', 'ACI', 'WCO', 'MWE', 'OVERALL'],
  SELECTION_CATEGORIES: ['leadership', 'roleplay', 'situational', 'interview', 'overall'],

  NOT_COMPLETE_PUPILLAGE_REASONS: {
    TRANSFERRED: 'transferred ',
    CALLED_PRE_2002: 'called-pre-2002',
    OTHER: 'other',
  },
};

export const TASK_TYPE = {
  SIFT: 'sift',
  SCENARIO: 'scenarioTest',
  CRITICAL_ANALYSIS: 'criticalAnalysis',
  SITUATIONAL_JUDGEMENT: 'situationalJudgement',
  QUALIFYING_TEST: 'qualifyingTest',
  TELEPHONE_ASSESSMENT: 'telephoneAssessment',
  ELIGIBILITY_SCC: 'eligibilitySCC',
  CHARACTER_AND_SELECTION_SCC: 'characterAndSelectionSCC',
  STATUTORY_CONSULTATION: 'statutoryConsultation',
  SHORTLISTING_OUTCOME: 'shortlistingOutcome',
  WELSH_ASSESSMENT: 'welshAssessment',
  PRE_SELECTION_DAY_QUESTIONNAIRE: 'preSelectionDayQuestionnaire',
  SELECTION_DAY: 'selectionDay',
  SELECTION_OUTCOME: 'selectionOutcome',
  EMP_TIEBREAKER: 'empTiebreaker',
};

export const SHORTLISTING_TASK_TYPES = [
  TASK_TYPE.TELEPHONE_ASSESSMENT,
  TASK_TYPE.SIFT,
  TASK_TYPE.CRITICAL_ANALYSIS,
  TASK_TYPE.SITUATIONAL_JUDGEMENT,
  TASK_TYPE.QUALIFYING_TEST,
  TASK_TYPE.SCENARIO,
];

export const TASK_STATUS = { // aka task STEPS
  CANDIDATE_FORM_CONFIGURE: 'candidateFormConfigure',
  CANDIDATE_FORM_MONITOR: 'candidateFormMonitor',
  DATA_INITIALISED: 'dataInitialised',
  DATA_ACTIVATED: 'dataActivated',
  TEST_INITIALISED: 'testInitialised',
  TEST_ACTIVATED: 'testActivated',
  PANELS_INITIALISED: 'panelsInitialised',
  PANELS_ACTIVATED: 'panelsActivated',
  MODERATION_INITIALISED: 'moderationInitialised',
  MODERATION_ACTIVATED: 'moderationActivated',
  STATUS_CHANGES: 'statusChanges',
  STAGE_OUTCOME: 'stageOutcome',
  FINALISED: 'finalised',
  CHECKS: 'checks',
  COMPLETED: 'completed',
};

export const CANDIDATE_FORM_STATUS = {
  CREATED: 'created',
  OPEN: 'open',
  CLOSED: 'closed',
};

export const CANDIDATE_FORM_RESPONSE_STATUS = {
  CREATED: 'created',
  REQUESTED: 'requested',
  COMPLETED: 'completed',
};

export const EXERCISE_STAGE = {
  // v2
  SHORTLISTING: 'shortlisting',
  SELECTION: 'selection',
  SCC: 'scc',
  RECOMMENDATION: 'recommendation',

  // v2 proposed but then removed
  APPLIED: 'applied', // to be removed
  SELECTABLE: 'selectable', // to be removed

  // v1
  REVIEW: 'review', // to be replaced with shortlisting
  SHORTLISTED: 'shortlisted', // to be replaced with selection
  SELECTED: 'selected', // to be replaced with recommendation
  RECOMMENDED: 'recommended', // to be replaced with recommendation
  HANDOVER: 'handover', // to be removed/replaced with recommendation
};

export const APPLICATION_STATUS = {
  // v2
  CRITICAL_ANALYSIS_PASSED: 'criticalAnalysisPassed',
  CRITICAL_ANALYSIS_FAILED: 'criticalAnalysisFailed',
  SITUATIONAL_JUDGEMENT_PASSED: 'situationalJudgementPassed',
  SITUATIONAL_JUDGEMENT_FAILED: 'situationalJudgementFailed',
  QUALIFYING_TEST_PASSED: 'qualifyingTestPassed',
  QUALIFYING_TEST_FAILED: 'qualifyingTestFailed',
  QUALIFYING_TEST_NOT_SUBMITTED: 'noTestSubmitted',
  SCENARIO_TEST_PASSED: 'scenarioTestPassed',
  SCENARIO_TEST_FAILED: 'scenarioTestFailed',
  SCENARIO_TEST_NOT_SUBMITTED: 'noScenarioTestSubmitted',
  SIFT_PASSED: 'siftPassed',
  SIFT_FAILED: 'siftFailed',
  TELEPHONE_ASSESSMENT_PASSED: 'telephoneAssessmentPassed',
  TELEPHONE_ASSESSMENT_FAILED: 'telephoneAssessmentFailed',
  SHORTLISTING_PASSED: 'shortlistingOutcomePassed',
  SHORTLISTING_FAILED: 'shortlistingOutcomeFailed',
  FULL_APPLICATION_NOT_SUBMITTED: 'fullApplicationNotSubmitted',
  ELIGIBILITY_SCC_PASSED: 'eligibilitySCCPassed',
  ELIGIBILITY_SCC_FAILED: 'eligibilitySCCFailed',
  CHARACTER_AND_SELECTION_SCC_PASSED: 'characterAndSelectionSCCPassed',
  CHARACTER_AND_SELECTION_SCC_FAILED: 'characterAndSelectionSCCFailed',
  STATUTORY_CONSULTATION_PASSED: 'statutoryConsultationPassed',
  STATUTORY_CONSULTATION_FAILED: 'statutoryConsultationFailed',
  SELECTION_INVITED: 'selectionInvited',
  REJECTED_INELIGIBLE_STATUTORY: 'rejectedIneligibleStatutory',
  REJECTED_INELIGIBLE_ADDITIONAL: 'rejectedIneligibleAdditional',
  REJECTED_CHARACTER: 'rejectedCharacter',
  SELECTION_DAY_PASSED: 'selectionDayPassed',
  SELECTION_DAY_FAILED: 'selectionDayFailed',
  SELECTION_PASSED: 'selectionOutcomePassed',
  SELECTION_FAILED: 'selectionOutcomeFailed',
  SELECTION_OUTCOME_PASSED: 'selectionOutcomePassed',
  SELECTION_OUTCOME_FAILED: 'selectionOutcomeFailed',
  PASSED_RECOMMENDED: 'passedRecommended',
  PASSED_NOT_RECOMMENDED: 'passedNotRecommended',
  RECOMMENDED_IMMEDIATE: 'recommendedImmediate',
  RECOMMENDED_FUTURE: 'recommendedFuture',
  RECONSIDER: 'reconsider',
  SECOND_STAGE_INVITED: 'secondStageInvited',
  SECOND_STAGE_PASSED: 'empTiebreakerPassed',
  SECOND_STAGE_FAILED: 'empTiebreakerFailed',
  APPROVED_IMMEDIATE: 'approvedImmediate',
  APPROVED_FUTURE: 'approvedFuture',
  WITHDRAWN: 'withdrawn',

  // v1 REVIEW
  PASSED_SIFT: 'passedSift',
  FAILED_SIFT: 'failedSift',
  SUBMITTED_FIRST_TEST: 'submittedFirstTest',
  FAILED_FIRST_TEST: 'failedFirstTest',
  SUBMITTED_SCENARIO_TEST: 'submittedScenarioTest',
  PASSED_FIRST_TEST: 'passedFirstTest',
  FAILED_SCENARIO_TEST: 'failedScenarioTest',
  PASSED_SCENARIO_TEST: 'passedScenarioTest',
  FAILED_TELEPHONE_ASSESSMENT: 'failedTelephoneAssessment',
  PASSED_TELEPHONE_ASSESSMENT: 'passedTelephoneAssessment',
  NO_TEST_SUBMITTED: 'noTestSubmitted',
  TEST_SUBMITTED_OVER_TIME: 'testSubmittedOverTime',
  WITHDREW_APPLICATION: 'withdrewApplication',
  REJECTED_AS_INELIGIBLE: 'rejectedAsIneligible',
  // v1 SHORTLISTED
  INVITED_TO_SELECTION_DAY: 'invitedToSelectionDay',
  // v1 SELECTED
  PASSED_SELECTION: 'passedSelection',
  FAILED_SELECTION: 'failedSelection',
  PASSED_BUT_NOT_RECOMMENDED: 'passedButNotRecommended',
  // v1 RECOMMENDED
  REJECTED_BY_CHARACTER: 'rejectedByCharacter',
  APPROVED_FOR_IMMEDIATE_APPOINTMENT: 'approvedForImmediateAppointment',
  APPROVED_FOR_FUTURE_APPOINTMENT: 'approvedForFutureAppointment',
  SCC_TO_RECONSIDER: 'sccToReconsider',
};

export const {
  APPLICATION,
  ASSESSMENT_METHOD,
  ASSESSMENT_TYPE,
  SHORTLISTING,
  QUALIFYING_TEST,
  QUALIFYING_TEST_RESPONSES,
  PANEL_STATUS,
  CAPABILITIES,
  SELECTION_CATEGORIES,
  NOT_COMPLETE_PUPILLAGE_REASONS,
} = CONSTANTS;
