name: Cloud Functions for Firebase

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'functions/**'
  push:
    branches:
      - develop
      - "**"
    paths:
      - 'functions/**'

concurrency:
  group: test_and_deploy
  cancel-in-progress: true

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run linting
      - name: Run lint
        run: npm run lint

      # Step 5: Test functions
      - name: Test functions
        run: npm run test:functions

      # Step 6: Test actions
      - name: Test actions
        run: echo "Under construction"
        # run: npm run test:actions

      # Step 7: Test shared
      - name: Test shared
        run: echo "Under construction"
        # run: npm run test:shared

      # Step 8: Authenticate with Google Cloud using Workload Identity Federation (WIF)
      - name: Authenticate with Google Cloud
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          version: 'v344.0.0'  # Replace with the correct version if necessary
          service_account_email: ${{ secrets.SERVICE_ACCOUNT }}
          project_id: digital-platform-develop

      # Step 9: Deploy to Firebase on push events
      # - name: Deploy to Firebase (for pushes)
      #   if: github.event_name == 'push' && success()
      #   run: npm run deploy:functions
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
