name: Cloud Workflow

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'functions/**'
  push:
    branches:
      - develop
    paths:
      - 'functions/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Authenticate with Google Cloud using WIF
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_pool: github-wif-pool 
          workload_identity_provider: githubwif
          service_account_email: ${{ secrets.SERVICE_ACCOUNT }}

      # Additional steps for build and deploy actions
      - name: Run Google Cloud CLI command
        run: |
          gcloud compute instances list

      # Example of using authenticated commands with Google Cloud SDK
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-service --image=gcr.io/my-project/my-image

      # Any other steps needed for your workflow

