name: Test GitHub Actions with Google Cloud

on:
  push:
    branches:
      - main

jobs:
  test_gcloud:
    runs-on: ubuntu-latest
    environment: develop
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_email: ${{ secrets.SERVICE_ACCOUNT }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
          project_id: digital-platform-develop
      
      - name: Authenticate with Workload Identity
        run: |
          gcloud auth login
          gcloud auth activate-service-account --key-file=${{ secrets.SERVICE_ACCOUNT }}
          gcloud config set auth/impersonate_service_account ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
      
      - name: List Google Cloud Storage buckets
        run: gcloud storage buckets list
