# name: Test GCP Authentication

# on:
#   push:
#     branches:
#       - '**'

# jobs:
#   auth:
#     runs-on: ubuntu-latest
#     environment: develop
#     permissions:
#       id-token: write
#       contents: read

#     steps:
#     - uses: actions/checkout@v4

#     - name: Authenticate to Google Cloud
#       id: auth
#       uses: google-github-actions/auth@v1
#       with:
#         workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_POOL_ID }}/providers/${{ secrets.OIDC_PROVIDER_ID }}"
#         service_account: "${{ secrets.GCP_OIDC_SERVICE_ACCOUNT_EMAIL }}"

#     - name: Test authentication
#       run: |
#         gcloud auth list
#         gcloud projects list
